// Author: Christopher Johnson [40275286]
// Class Purpose: Car Hire class to store car hire information
// Date Last Modified: 10/12/2017

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Business
{
    public class CarHire
    {
        // Declare the attributes for the car hire class
        private DateTime _hireStart;
        private DateTime _hireEnd;
        private long _driverPass;
        private int _carHireRef;

        public DateTime hireStart
        {
            get
            {
                return _hireStart;
            }
            set
            {
                // Validate
                if (value == null)
                {
                    throw new ArgumentException("Arrival Date cannot be blank");
                }
                _hireStart = value;
            }
        }

        public DateTime hireEnd
        {
            get
            {
                return _hireEnd;
            }
            set
            {
                // Validate
                if (value == null)
                {
                    throw new ArgumentException("Arrival Date cannot be blank");
                }
                _hireEnd = value;
            }
        }

        public long driverPass
        {
            get
            {
                return _driverPass;
            }
            set
            {
                _driverPass = value;
            }
        }

        public int carHireRef
        {
            get
            {
                return _carHireRef;
            }
            set
            {
                // Is autogenerated no need for validation
                _carHireRef = value;
            }
        }
    }
}
